services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
  user-service:
    build: ./user-service
    ports:
      - "8000:8000"
    volumes:
      - ./user-service/chroma_index:/usr/src/app/chroma_index
  redis:
    image: redis
    container_name: redis_cache
  elasticsearch:
    image: elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
  kibana:
    image: kibana:7.9.2
    ports:
      - "5601:5601"
